name: photoname
version: '5.0'
license: ISC
copyright: 2007-2021 Dino Morelli
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
stability: stable
homepage: http://hub.darcs.net/dino/photoname
synopsis: Rename photo image files based on EXIF shoot date
description: Command-line utility for renaming/moving photo image files based on EXIF tags.
category: Application, Console
tested-with: GHC >= 8.2.2

extra-source-files:
- changelog.md
- doc/hcar-photoname.tex
- .gitignore
- package.yaml
- README.md
- stack.yaml
- util/resources/appimage/*
- util/resources/test/*

github: dino-/photoname

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.5 && < 5.0
- directory
- filepath
- unix

library:
  source-dirs: src/lib
  dependencies:
  - containers
  - hsexif
  - mtl
  - parsec
  - process
  - time

executables:
  photoname:
    source-dirs: src/app
    main: photoname.hs
    dependencies:
    - ansi-wl-pprint
    - heredoc
    - optparse-applicative
    - photoname

tests:
  photoname-tests:
    source-dirs: src/tests
    main: runtests.hs
    dependencies:
    - photoname
    - process
    - regex-posix
    - time
    - tasty
    - tasty-hunit
    - tasty-quickcheck
